// <auto-generated />
using System;
using MeControla.AgileManager.DataStorage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeControla.AgileManager.DataStorage.Migrations
{
    [DbContext(typeof(DbAppContext))]
    [Migration("20220809122250_Migration001")]
    partial class Migration001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("MeControla.AgileManager.Data.Entities.Issue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("iss_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("iss_created");

                    b.Property<DateTime?>("CustomField14503")
                        .HasColumnType("TEXT")
                        .HasColumnName("iss_custom_field14503");

                    b.Property<bool>("Incident")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("iss_incident");

                    b.Property<long>("IssueTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("istp_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("iss_key");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("iss_link");

                    b.Property<long>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prj_id");

                    b.Property<DateTime?>("Resolved")
                        .HasColumnType("TEXT")
                        .HasColumnName("iss_resolved");

                    b.Property<long>("StatusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stt_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("iss_summary");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT")
                        .HasColumnName("iss_updated");

                    b.Property<Guid>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("iss_uuid");

                    b.HasKey("Id");

                    b.HasIndex("IssueTypeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StatusId");

                    b.ToTable("am_issue", "agile_manager");
                });

            modelBuilder.Entity("MeControla.AgileManager.Data.Entities.IssueEpic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("isep_id");

                    b.Property<long>("IssueId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("iss_id");

                    b.Property<decimal>("Progress")
                        .HasColumnType("TEXT")
                        .HasColumnName("isep_progress");

                    b.Property<long?>("QuarterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("qrt_id");

                    b.Property<Guid>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("isep_uuid");

                    b.HasKey("Id");

                    b.HasIndex("IssueId")
                        .IsUnique();

                    b.HasIndex("QuarterId");

                    b.ToTable("am_issue_epic", "agile_manager");
                });

            modelBuilder.Entity("MeControla.AgileManager.Data.Entities.IssueImpediment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("isim_id");

                    b.Property<DateTime?>("End")
                        .HasColumnType("TEXT")
                        .HasColumnName("isim_end");

                    b.Property<long>("IssueId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("iss_id");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT")
                        .HasColumnName("isim_start");

                    b.Property<Guid>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("isim_uuid");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("am_issue_impediment", "agile_manager");
                });

            modelBuilder.Entity("MeControla.AgileManager.Data.Entities.IssueStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ish_id");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("ish_date_time");

                    b.Property<long>("IssueId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isep_id");

                    b.Property<long>("StatusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stt_id");

                    b.Property<Guid>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("ish_uuid");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("StatusId");

                    b.ToTable("am_issue_status_history", "agile_manager");
                });

            modelBuilder.Entity("MeControla.AgileManager.Data.Entities.IssueType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("istp_id");

                    b.Property<long>("Key")
                        .HasColumnType("INTEGER")
                        .HasColumnName("istp_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("istp_name");

                    b.Property<Guid>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("istp_uuid");

                    b.HasKey("Id");

                    b.ToTable("am_issue_type", "agile_manager");
                });

            modelBuilder.Entity("MeControla.AgileManager.Data.Entities.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("prj_id");

                    b.Property<long>("Key")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prj_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("prj_name");

                    b.Property<long>("ProjectCategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prj_project_category_id");

                    b.Property<bool>("Selected")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prj_selected");

                    b.Property<Guid>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("prj_uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectCategoryId");

                    b.ToTable("am_project", "agile_manager");
                });

            modelBuilder.Entity("MeControla.AgileManager.Data.Entities.ProjectCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pjct_id");

                    b.Property<long>("Key")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pjct_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("pjct_name");

                    b.Property<Guid>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("pjct_uuid");

                    b.HasKey("Id");

                    b.ToTable("am_project_category", "agile_manager");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Key = 0L,
                            Name = "No Category",
                            Uuid = new Guid("042b72f2-0848-47a1-bb11-8ed69b0caf7e")
                        },
                        new
                        {
                            Id = 2L,
                            Key = 12904L,
                            Name = "Aplicativos",
                            Uuid = new Guid("15792637-4496-4e0f-8848-e3ee2b077711")
                        },
                        new
                        {
                            Id = 3L,
                            Key = 11404L,
                            Name = "Decisão",
                            Uuid = new Guid("975a10e5-74fa-4529-baf7-c08d79d62c9a")
                        },
                        new
                        {
                            Id = 4L,
                            Key = 11104L,
                            Name = "Descoberta",
                            Uuid = new Guid("b1c8348f-aa66-46fd-97bd-2ffe97d681bb")
                        },
                        new
                        {
                            Id = 5L,
                            Key = 12905L,
                            Name = "Fidelização",
                            Uuid = new Guid("dc5e09d1-610d-4ced-9c06-e014fc2b2beb")
                        });
                });

            modelBuilder.Entity("MeControla.AgileManager.Data.Entities.Quarter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("qrt_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("qrt_name");

                    b.Property<Guid>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("qrt_uuid");

                    b.HasKey("Id");

                    b.ToTable("am_quarter", "agile_manager");
                });

            modelBuilder.Entity("MeControla.AgileManager.Data.Entities.Status", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("stt_id");

                    b.Property<long>("Key")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stt_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("stt_name");

                    b.Property<long>("StatusCategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stct_id");

                    b.Property<Guid>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("stt_uuid");

                    b.HasKey("Id");

                    b.HasIndex("StatusCategoryId");

                    b.ToTable("am_status", "agile_manager");
                });

            modelBuilder.Entity("MeControla.AgileManager.Data.Entities.StatusCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("stct_id");

                    b.Property<long>("Key")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stct_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("stct_name");

                    b.Property<Guid>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("stct_uuid");

                    b.HasKey("Id");

                    b.ToTable("am_status_category", "agile_manager");
                });

            modelBuilder.Entity("MeControla.AgileManager.Data.Entities.Issue", b =>
                {
                    b.HasOne("MeControla.AgileManager.Data.Entities.IssueType", "IssueType")
                        .WithMany("Issues")
                        .HasForeignKey("IssueTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeControla.AgileManager.Data.Entities.Project", "Project")
                        .WithMany("Issues")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeControla.AgileManager.Data.Entities.Status", "Status")
                        .WithMany("Issues")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IssueType");

                    b.Navigation("Project");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MeControla.AgileManager.Data.Entities.IssueEpic", b =>
                {
                    b.HasOne("MeControla.AgileManager.Data.Entities.Issue", "Issue")
                        .WithOne("IssueEpic")
                        .HasForeignKey("MeControla.AgileManager.Data.Entities.IssueEpic", "IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeControla.AgileManager.Data.Entities.Quarter", "Quarter")
                        .WithMany("Epics")
                        .HasForeignKey("QuarterId");

                    b.Navigation("Issue");

                    b.Navigation("Quarter");
                });

            modelBuilder.Entity("MeControla.AgileManager.Data.Entities.IssueImpediment", b =>
                {
                    b.HasOne("MeControla.AgileManager.Data.Entities.Issue", "Issue")
                        .WithMany("Impediments")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("MeControla.AgileManager.Data.Entities.IssueStatusHistory", b =>
                {
                    b.HasOne("MeControla.AgileManager.Data.Entities.Issue", "Issue")
                        .WithMany("Statuses")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeControla.AgileManager.Data.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MeControla.AgileManager.Data.Entities.Project", b =>
                {
                    b.HasOne("MeControla.AgileManager.Data.Entities.ProjectCategory", "ProjectCategory")
                        .WithMany("Projects")
                        .HasForeignKey("ProjectCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectCategory");
                });

            modelBuilder.Entity("MeControla.AgileManager.Data.Entities.Status", b =>
                {
                    b.HasOne("MeControla.AgileManager.Data.Entities.StatusCategory", "StatusCategory")
                        .WithMany("Statuses")
                        .HasForeignKey("StatusCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusCategory");
                });

            modelBuilder.Entity("MeControla.AgileManager.Data.Entities.Issue", b =>
                {
                    b.Navigation("Impediments");

                    b.Navigation("IssueEpic");

                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("MeControla.AgileManager.Data.Entities.IssueType", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("MeControla.AgileManager.Data.Entities.Project", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("MeControla.AgileManager.Data.Entities.ProjectCategory", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("MeControla.AgileManager.Data.Entities.Quarter", b =>
                {
                    b.Navigation("Epics");
                });

            modelBuilder.Entity("MeControla.AgileManager.Data.Entities.Status", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("MeControla.AgileManager.Data.Entities.StatusCategory", b =>
                {
                    b.Navigation("Statuses");
                });
#pragma warning restore 612, 618
        }
    }
}
