name: Coveralls

on:
  push:
    branches: [ main, develop ]
env:
  path-lcov: './Stefanini.ViaReport.Core.Tests'
  filename-lcov: 'coverage.info'
  coveralls-service-name: 'Git Hub Action'

jobs:
  build-test:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Generate coverage report
      run: dotnet test --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=lcov

    - name: Save coverage file
      uses: actions/upload-artifact@master
      with:
        name: coverage-file
        path: ${{ env.path-lcov }}

  publish:
    needs: build-test
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Load coverage file
      uses: actions/download-artifact@master
      with:
        name: coverage-file
        path: ${{ env.path-lcov }}
        
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    
    - name: Publish coverage report to coveralls.io
      run: |
        dotnet new tool-manifest
        dotnet tool install coveralls.net --tool-path tools
        dotnet tool restore
        
        $coveralls = ".\tools\csmacnz.coveralls.exe"
        
        & $coveralls --repoToken ${{ secrets.COVERALLS_REPO_TOKEN }} --commitBranch "${{ steps.extract_branch.outputs.branch }}" --serviceName "${{ env.coveralls-service-name }}" --lcov -i ${{ env.path-lcov }}/${{ env.filename-lcov }} --useRelativePaths --commitId ${{ github.sha }}