name: Coveralls

on:
  pull_request:
    branches: [ main, develop ]
    types: [closed]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
        file-lcov-path: [ './Stefanini.ViaReport.Core.Tests/coverage.info' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Generate coverage report
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov

    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GIT_TOKEN }}
        git-branch: ${{ github.ref }}
        path-to-lcov: ${{ matrix.file-lcov-path }}