name: .NET

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
        build-configuration: [ 'Release' ]

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration ${{ matrix.build-configuration }}

    - name: Test
      run: dotnet test --no-restore --no-build --verbosity normal --configuration ${{ matrix.build-configuration }}
